#!/bin/bash
#===============================================================================
# STING Backup Cron Setup Script
# Installs and configures automated backup cron jobs
#===============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALL_DIR="${INSTALL_DIR:-$(dirname "$SCRIPT_DIR"/../..)}"
BACKUP_SCRIPT="${SCRIPT_DIR}/backup-wrapper.sh"
MONITOR_SCRIPT="${SCRIPT_DIR}/backup-monitor.sh"
VAULT_SCRIPT="${INSTALL_DIR}/vault/scripts/backup-vault.sh"
CRON_FILE="/etc/cron.d/sting-backup"
BACKUP_USER="${BACKUP_USER:-root}"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

#===============================================================================
# Check prerequisites
#===============================================================================
check_prerequisites() {
    log_info "Checking prerequisites..."

    local missing=()

    if [ ! -f "$BACKUP_SCRIPT" ]; then
        missing+=("$BACKUP_SCRIPT")
    fi

    if [ ! -f "$MONITOR_SCRIPT" ]; then
        missing+=("$MONITOR_SCRIPT")
    fi

    if [ ${#missing[@]} -gt 0 ]; then
        log_error "Missing required scripts: ${missing[*]}"
        return 1
    fi

    # Check if cron is available
    if ! command -v cron >/dev/null 2>&1 && ! command -v crond >/dev/null 2>&1; then
        log_warn "cron/crond not found - cron jobs will not be started"
    fi

    log_info "Prerequisites check passed"
    return 0
}

#===============================================================================
# Generate cron configuration
#===============================================================================
generate_cron_config() {
    local backup_dir="${1:-/opt/sting-backups}"
    local backup_user="${2:-$BACKUP_USER}"

    cat << EOF
# STING Backup Cron Jobs
# Generated by setup-backup-cron.sh
# Edit this file or re-run setup to update

SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
MAILTO=root

# Environment variables
STING_INSTALL_DIR=$INSTALL_DIR
BACKUP_DIR=$backup_dir

#---------------------------------------------------------------------------
# STING Backup Jobs
#---------------------------------------------------------------------------

# Daily full backup at 2:30 AM
30 2 * * * $backup_user $BACKUP_SCRIPT backup --directory $backup_dir >> $backup_dir/backup.log 2>&1

# Weekly full backup with encryption on Sunday at 3:30 AM
30 3 * * 0 $backup_user $BACKUP_SCRIPT backup --directory $backup_dir --encrypt >> $backup_dir/backup.log 2>&1

# Vault backup every 6 hours
0 */6 * * * $backup_user $VAULT_SCRIPT >> /vault/backups/vault_backup.log 2>&1

#---------------------------------------------------------------------------
# STING Backup Monitoring Jobs
#---------------------------------------------------------------------------

# Hourly backup freshness check
0 * * * * $backup_user $MONITOR_SCRIPT freshness --backup-dir $backup_dir

# Daily comprehensive health check at 6 AM
0 6 * * * $backup_user $MONITOR_SCRIPT check --backup-dir $backup_dir

# Weekly integrity verification on Sunday at 7 AM
0 7 * * 0 $backup_user $MONITOR_SCRIPT integrity --backup-dir $backup_dir

#---------------------------------------------------------------------------
# Backup Rotation (daily at 4 AM)
#---------------------------------------------------------------------------
0 4 * * * $backup_user $BACKUP_SCRIPT rotate --directory $backup_dir

EOF
}

#===============================================================================
# Install cron jobs
#===============================================================================
install_cron() {
    local backup_dir="${1:-/opt/sting-backups}"
    local install_cron_file="${2:-$CRON_FILE}"

    log_info "Installing backup cron jobs to $install_cron_file..."

    # Create backup directory
    mkdir -p "$backup_dir"
    mkdir -p "$(dirname "$install_cron_file")"

    # Generate and install cron file
    generate_cron_config "$backup_dir" "$BACKUP_USER" > "$install_cron_file"

    # Set permissions
    chmod 644 "$install_cron_file"

    # Restart cron service
    if command -v systemctl >/dev/null 2>&1; then
        if systemctl is-active --quiet cron 2>/dev/null; then
            systemctl restart cron
            log_info "Restarted cron service"
        elif systemctl is-active --quiet crond 2>/dev/null; then
            systemctl restart crond
            log_info "Restarted crond service"
        else
            log_warn "cron service not running - will start on next boot"
        fi
    elif command -v service >/dev/null 2>&1; then
        service cron restart 2>/dev/null || service crond restart 2>/dev/null || log_warn "Could not restart cron service"
    else
        log_warn "No service manager found - cron jobs will activate on next cron restart"
    fi

    log_info "Cron jobs installed successfully"
}

#===============================================================================
# Show current cron status
#===============================================================================
show_cron_status() {
    log_info "Current backup cron configuration:"
    echo ""

    if [ -f "$CRON_FILE" ]; then
        cat "$CRON_FILE"
    else
        echo "Cron file not installed: $CRON_FILE"
    fi

    echo ""
    log_info "Next scheduled backup jobs:"
    if command -v nextcron >/dev/null 2>&1; then
        nextcron "$CRON_FILE" 2>/dev/null || true
    else
        echo "(Install 'nextcron' tool to see scheduled times)"
    fi
}

#===============================================================================
# Remove cron jobs
#===============================================================================
remove_cron() {
    log_info "Removing backup cron jobs..."

    if [ -f "$CRON_FILE" ]; then
        rm -f "$CRON_FILE"
        log_info "Removed $CRON_FILE"
    else
        log_warn "Cron file not found: $CRON_FILE"
    fi

    # Restart cron to pick up changes
    if command -v systemctl >/dev/null 2>&1; then
        systemctl restart cron 2>/dev/null || systemctl restart crond 2>/dev/null || true
    fi

    log_info "Backup cron jobs removed"
}

#===============================================================================
# Show help
#===============================================================================
show_help() {
    cat << EOF
STING Backup Cron Setup Script

Usage: $0 <command> [options]

Commands:
    install       Install backup cron jobs (default)
    status        Show current cron configuration
    remove        Remove all backup cron jobs
    help          Show this help

Options:
    --backup-dir DIR     Backup directory (default: /opt/sting-backups)
    --cron-file FILE     Cron file path (default: /etc/cron.d/sting-backup)
    --user USER          User to run backups (default: root)

Examples:
    $0 install                          # Install with defaults
    $0 install --backup-dir /data/backups   # Custom backup directory
    $0 install --user sting              # Run as sting user
    $0 status                            # Show current configuration
    $0 remove                            # Remove all backup cron jobs

Cron Schedule Reference:
    - Daily backup:      30 2 * * *
    - Weekly backup:     30 3 * * 0
    - Vault backup:      0 */6 * * *
    - Freshness check:   0 * * * *
    - Health check:      0 6 * * *
    - Integrity check:   0 7 * * 0
    - Rotation:          0 4 * * *

EOF
}

#===============================================================================
# Main entry point
#===============================================================================
main() {
    local command="install"
    local backup_dir="/opt/sting-backups"
    local cron_file="$CRON_FILE"

    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case "$1" in
            install|status|remove|help)
                command="$1"
                shift
                ;;
            --backup-dir)
                backup_dir="$2"
                shift 2
                ;;
            --cron-file)
                cron_file="$2"
                shift 2
                ;;
            --user)
                BACKUP_USER="$2"
                shift 2
                ;;
            *)
                echo "Unknown option: $1"
                show_help
                exit 1
                ;;
        esac
    done

    # Execute command
    case "$command" in
        install)
            check_prerequisites || exit 1
            install_cron "$backup_dir" "$cron_file"
            ;;
        status)
            show_cron_status
            ;;
        remove)
            remove_cron
            ;;
        help)
            show_help
            ;;
        *)
            echo "Unknown command: $command"
            show_help
            exit 1
            ;;
    esac
}

main "$@"
