apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    editable: false
    jsonData:
      maxLines: 1000
      timeout: 60s
      derivedFields:
        - name: TraceID
          matcherRegex: trace_id=(\w+)
          url: "$${__value.raw}"
        - name: UserID
          matcherRegex: user_id=([a-zA-Z0-9-]+)
          url: ""
    version: 1