# config_schema.py

SCHEMA = {
    'INSTALL_DIR': {'type': 'string', 'required': True},
    'REQUIRED_STING_VERSION': {'type': 'string', 'required': True},
    'APP_PORT': {'type': 'integer', 'required': True, 'coerce': int},
    'FLASK_APP': {'type': 'string', 'required': True},
    'FLASK_DEBUG': {'type': 'boolean', 'required': True},
    'APP_ENV': {'type': 'string', 'required': True},
    'APP_HOST': {'type': 'string', 'required': True},
    'LOG_MAX_SIZE': {'type': 'integer', 'required': True, 'coerce': int},
    'OIDC_CLIENT_SECRETS': {'type': 'string', 'required': True},
    'REACT_PORT': {'type': 'integer', 'required': True, 'coerce': int},
    'POSTGRES_USER': {'type': 'string', 'required': True},
    'POSTGRES_PASSWORD': {'type': 'string', 'required': True},
    'DB_PORT': {'type': 'integer', 'required': True, 'coerce': int},
    'KEYCLOAK_USER': {'type': 'string', 'required': True},
    'KC_BOOTSTRAP_ADMIN_PASSWORD': {'type': 'string', 'required': True},
    'KC_DB': {'type': 'string', 'required': True},
    'KC_DB_URL': {'type': 'string', 'required': True},
    'KC_DB_USERNAME': {'type': 'string', 'required': True},
    'KC_DB_PASSWORD': {'type': 'string', 'required': True},
    'KC_HTTP_PORT': {'type': 'integer', 'required': True, 'coerce': int},
    'KC_HTTPS_PORT': {'type': 'integer', 'required': True, 'coerce': int},
    'KC_HEALTH_ENABLED': {'type': 'string', 'required': True},
    'KC_METRICS_ENABLED': {'type': 'string', 'required': True},
    'KC_BOOTSTRAP_ADMIN_USERNAME': {'type': 'string', 'required': True},
    'KC_BOOTSTRAP_ADMIN_PASSWORD': {'type': 'string', 'required': True},
    'KC_HOSTNAME': {'type': 'string', 'required': True},
    'KEYSTORE_PASSWORD': {'type': 'string', 'required': True},
    'KEYCLOAK_SECRET': {'type': 'string', 'required': True},
    'KEYCLOAK_REDIRECT_URI': {'type': 'string', 'required': True},
    'KEYCLOAK_CLIENT_ID': {'type': 'string', 'required': True},
    'KEYCLOAK_URL': {'type': 'string', 'required': True},
    'KEYCLOAK_REALM': {'type': 'string', 'required': True},
    'NEXT_PUBLIC_KEYCLOAK_URL': {'type': 'string', 'required': True},
    'NEXT_PUBLIC_KEYCLOAK_REALM': {'type': 'string', 'required': True},
    'NEXT_PUBLIC_KEYCLOAK_CLIENT_ID': {'type': 'string', 'required': True},
    'NEXT_PUBLIC_KEYCLOAK_REDIRECT_URI': {'type': 'string', 'required': True},
    'VOLUME_REALM_EXPORT': {'type': 'string', 'required': True},
    'VOLUME_REALM_EXPORT_PATH': {'type': 'string', 'required': True},
    'VOLUME_INIT_DB': {'type': 'string', 'required': True},
    'VOLUME_INIT_DB_PATH': {'type': 'string', 'required': True},
    'BACKUP_DEFAULT_DIRECTORY': {'type': 'string', 'required': True},
    'BACKUP_CUSTOM_DIRECTORY': {'type': 'string', 'required': False},
    'BACKUP_COMPRESSION_LEVEL': {'type': 'integer', 'required': True, 'coerce': int},
    'BACKUP_RETENTION_COUNT': {'type': 'integer', 'required': True, 'coerce': int},
    'BACKUP_EXCLUDE_PATTERNS': {'type': 'string', 'required': True},
}

SENSITIVE_FIELDS = [
    'POSTGRES_PASSWORD',
    'KC_BOOTSTRAP_ADMIN_PASSWORD',
    'KC_DB_PASSWORD',
    'KC_BOOTSTRAP_ADMIN_PASSWORD',
    'KEYCLOAK_SECRET',
    'KEYSTORE_PASSWORD'
]