-- Bee Conversation History Schema for STING CE
-- Persistent storage for conversation history with future-proof design
-- Supports: PostgreSQL, TimescaleDB (medium-term), CockroachDB (long-term)

\c sting_messaging;

-- ============================================================================
-- CONVERSATIONS TABLE
-- Stores conversation metadata and settings
-- ============================================================================
CREATE TABLE IF NOT EXISTS conversations (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

    -- User association (matches Kratos identity ID)
    user_id UUID NOT NULL,

    -- Optional bot association (for Nectar Bot conversations)
    bot_id UUID DEFAULT NULL,

    -- Conversation metadata
    title VARCHAR(255) DEFAULT NULL,  -- Auto-generated or user-set title
    conversation_type VARCHAR(50) DEFAULT 'bee_chat',  -- bee_chat, nectar_bot, support

    -- State management
    status VARCHAR(20) DEFAULT 'active',  -- active, archived, deleted
    is_pinned BOOLEAN DEFAULT FALSE,

    -- Context settings (stored as JSONB for flexibility)
    settings JSONB DEFAULT '{}',
    -- Example settings:
    -- {
    --   "honey_jar_id": "uuid",
    --   "model_override": "gpt-4",
    --   "temperature": 0.7,
    --   "system_prompt_override": null
    -- }

    -- Summary for long conversations (generated by ConversationSummarizer)
    summary JSONB DEFAULT NULL,
    -- Example summary:
    -- {
    --   "text": "Discussion about STING security features...",
    --   "topics": ["security", "authentication"],
    --   "key_points": ["Implemented passkeys", "Added TOTP"],
    --   "last_summarized_at": "2025-01-15T10:30:00Z",
    --   "messages_summarized": 20
    -- }

    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    last_message_at TIMESTAMPTZ DEFAULT NOW(),

    -- Soft delete support
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

-- ============================================================================
-- MESSAGES TABLE
-- Stores individual messages with time-series optimization
-- Designed for TimescaleDB hypertable conversion (medium-term)
-- ============================================================================
CREATE TABLE IF NOT EXISTS messages (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

    -- Foreign key to conversation
    conversation_id UUID NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,

    -- Message content
    role VARCHAR(20) NOT NULL,  -- user, assistant, system
    content TEXT NOT NULL,

    -- Token tracking (useful for context management)
    token_count INTEGER DEFAULT NULL,

    -- Message metadata (flexible JSONB)
    metadata JSONB DEFAULT '{}',
    -- Example metadata:
    -- {
    --   "model": "qwen2.5-14b-instruct",
    --   "processing_time_ms": 2500,
    --   "honey_jar_context": true,
    --   "pii_detected": false,
    --   "tools_used": ["report_generation"],
    --   "semantic_indexed": true
    -- }

    -- Timestamps (critical for time-series queries)
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,

    -- Soft delete support
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

-- ============================================================================
-- CONVERSATION SUMMARIES TABLE (for ConversationSummarizer)
-- Stores historical summaries as conversations grow
-- ============================================================================
CREATE TABLE IF NOT EXISTS conversation_summaries (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

    conversation_id UUID NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,

    -- Summary content
    summary_text TEXT NOT NULL,
    topics TEXT[] DEFAULT '{}',
    key_points TEXT[] DEFAULT '{}',
    entities TEXT[] DEFAULT '{}',
    action_items TEXT[] DEFAULT '{}',

    -- Range of messages summarized
    message_count INTEGER NOT NULL,
    start_message_id UUID DEFAULT NULL,
    end_message_id UUID DEFAULT NULL,
    start_timestamp TIMESTAMPTZ,
    end_timestamp TIMESTAMPTZ,

    -- Generation metadata
    generated_by VARCHAR(50) DEFAULT 'fallback',  -- llm, fallback
    model_used VARCHAR(100) DEFAULT NULL,

    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================================
-- INDEXES
-- Optimized for common query patterns
-- ============================================================================

-- Conversations: User lookup (most common query)
CREATE INDEX IF NOT EXISTS idx_conversations_user_id
    ON conversations(user_id);

-- Conversations: User + status for active conversations list
CREATE INDEX IF NOT EXISTS idx_conversations_user_status
    ON conversations(user_id, status)
    WHERE deleted_at IS NULL;

-- Conversations: Last message time for sorting
CREATE INDEX IF NOT EXISTS idx_conversations_last_message
    ON conversations(user_id, last_message_at DESC)
    WHERE deleted_at IS NULL;

-- Conversations: Bot lookup (for Nectar Bot analytics)
CREATE INDEX IF NOT EXISTS idx_conversations_bot_id
    ON conversations(bot_id)
    WHERE bot_id IS NOT NULL;

-- Messages: Conversation lookup (primary access pattern)
CREATE INDEX IF NOT EXISTS idx_messages_conversation_id
    ON messages(conversation_id);

-- Messages: Time-based retrieval (for context loading)
CREATE INDEX IF NOT EXISTS idx_messages_conversation_time
    ON messages(conversation_id, created_at DESC);

-- Messages: Role filtering (for user message count, etc.)
CREATE INDEX IF NOT EXISTS idx_messages_conversation_role
    ON messages(conversation_id, role);

-- Summaries: Conversation lookup
CREATE INDEX IF NOT EXISTS idx_summaries_conversation_id
    ON conversation_summaries(conversation_id);

-- ============================================================================
-- TRIGGERS
-- Auto-update timestamps and conversation metadata
-- ============================================================================

-- Function to update conversation's last_message_at and updated_at
CREATE OR REPLACE FUNCTION update_conversation_timestamps()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE conversations
    SET
        last_message_at = NEW.created_at,
        updated_at = NOW()
    WHERE id = NEW.conversation_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger: Update conversation when new message is inserted
DROP TRIGGER IF EXISTS trigger_update_conversation_on_message ON messages;
CREATE TRIGGER trigger_update_conversation_on_message
    AFTER INSERT ON messages
    FOR EACH ROW
    EXECUTE FUNCTION update_conversation_timestamps();

-- Function to auto-update updated_at on conversations
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger: Auto-update updated_at on conversation changes
DROP TRIGGER IF EXISTS trigger_conversations_updated_at ON conversations;
CREATE TRIGGER trigger_conversations_updated_at
    BEFORE UPDATE ON conversations
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- TIMESCALEDB PREPARATION (Medium-term optimization)
-- Uncomment these when TimescaleDB extension is available
-- ============================================================================
--
-- -- Convert messages to hypertable for time-series optimization
-- SELECT create_hypertable('messages', 'created_at',
--     chunk_time_interval => INTERVAL '7 days',
--     if_not_exists => TRUE
-- );
--
-- -- Enable compression on older chunks
-- ALTER TABLE messages SET (
--     timescaledb.compress,
--     timescaledb.compress_segmentby = 'conversation_id',
--     timescaledb.compress_orderby = 'created_at DESC'
-- );
--
-- -- Add compression policy (compress chunks older than 30 days)
-- SELECT add_compression_policy('messages', INTERVAL '30 days');
--
-- -- Add retention policy (optional - delete messages older than 1 year)
-- -- SELECT add_retention_policy('messages', INTERVAL '365 days');

-- ============================================================================
-- PERMISSIONS
-- Grant appropriate permissions to service users
-- ============================================================================

-- Grant full access to messaging_user (primary)
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO messaging_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO messaging_user;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO messaging_user;

-- Grant full access to app_user (for cross-service operations)
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO app_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO app_user;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO app_user;

-- ============================================================================
-- INITIAL DATA / MIGRATIONS
-- ============================================================================

-- Version tracking for schema migrations
CREATE TABLE IF NOT EXISTS schema_version (
    version INTEGER PRIMARY KEY,
    description TEXT,
    applied_at TIMESTAMPTZ DEFAULT NOW()
);

-- Record this schema version
INSERT INTO schema_version (version, description)
VALUES (1, 'Initial Bee conversation schema with TimescaleDB preparation')
ON CONFLICT (version) DO NOTHING;

-- ============================================================================
-- SUCCESS LOG
-- ============================================================================
DO $$
BEGIN
    RAISE NOTICE '✅ Bee conversation schema created successfully';
    RAISE NOTICE '   Tables: conversations, messages, conversation_summaries';
    RAISE NOTICE '   Indexes: Optimized for user lookup and time-series queries';
    RAISE NOTICE '   Triggers: Auto-update timestamps on message insert';
    RAISE NOTICE '   Ready for: PostgreSQL, TimescaleDB, CockroachDB migration';
END $$;
