FROM python:3.12.8-slim

ARG POSTGRESQL_USER
#ARG POSTGRESQL_PASSWORD
ARG POSTGRESQL_DATABASE_NAME
ARG POSTGRESQL_HOST
ARG POSTGRESQL_PORT

# Set environment variables
ENV POSTGRESQL_USER=${POSTGRESQL_USER} \
    #POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD} \
    POSTGRESQL_DATABASE_NAME=${POSTGRESQL_DATABASE_NAME} \
    POSTGRESQL_HOST=${POSTGRESQL_HOST} \
    POSTGRESQL_PORT=${POSTGRESQL_PORT}

# Set working directory 

WORKDIR /app

# Create conf directory
RUN mkdir -p /app/conf

# Copy configuration files
COPY ./conf/ /app/conf/


# Set permissions
RUN chmod -R 755 /app/conf/ && \
    find /app/conf/ -type f -exec chmod 644 {} \;
# Clear Python cache during build
RUN find . -type f -name "*.pyc" -delete && \
    find . -type d -name "__pycache__" -delete

# Install dependencies
RUN pip install pyyaml hvac requests

# Run config_loader
CMD ["sh", "-c", "python /app/conf/config_loader.py /app/conf/config.yml"]