version: '3.8'

services:
  test-chatbot:
    build:
      context: ..
      dockerfile: ./test-chatbot/Dockerfile
    container_name: sting-test-chatbot
    environment:
      - PORT=8082
      - HOST=0.0.0.0
      - LOG_LEVEL=DEBUG
      - CHATBOT_NAME=TestBee
      - CHATBOT_MODEL=llama3
      - CHATBOT_CONTEXT_WINDOW=10
      - CHATBOT_SYSTEM_PROMPT=You are TestBee, a test assistant for the STING platform.
      - CHATBOT_TOOLS_ENABLED=true
      - CHATBOT_ALLOWED_TOOLS=search,summarize,analyze
      - CHATBOT_REQUIRE_AUTH=false
      - CHATBOT_LOG_CONVERSATIONS=true
      - CHATBOT_CONTENT_FILTER_LEVEL=none
      - LLM_GATEWAY_URL=http://sting-ce-llm-gateway-1:8080
      - PYTHONPATH=/app
    volumes:
      - ../chatbot:/app/chatbot
      - ../llm_service/chat:/app/llm_service/chat
      - ../llm_service/filtering:/app/llm_service/filtering
      - ${HOME}/Downloads/llm_models:/app/models
    ports:
      - "8082:8082"
    networks:
      - default
      - sting_local
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8082/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  sting_local:
    external: true